import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@/styles/globals.scss"
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import SessionWrapper from "@/components/SeassonWrapper";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="body--container">
                <SessionWrapper>
                <Navbar/>
                {children}
                <Footer/>
                </SessionWrapper>
            </body>
        </html>
    );
}
